accounts/urls.py
from django.conf.urls import url
from accounts import views

app_name = 'accounts'

urlpatterns = [
    url(r'^register/$', views.register_member, name='register-member'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

prepair/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from rest_framework.routers import DefaultRouter

from prepair import views

from airports.views import AirportViewSet, RunwayViewSet, AirportCommViewSet
from accounts.views import MemberViewSet, UserViewSet
from communication.views import PostViewSet, CommentViewSet

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index-view'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^dashboard/?', views.DashboardTemplateView.as_view(), name='dashboard'),
    url(r'^api-auth/', include('rest_framework.urls')),
]

# Below are the DRF-Ember Router URL patterns

router = DefaultRouter(trailing_slash=False)
router.register(r'airports', AirportViewSet, base_name='serializers-airport')
router.register(r'runways', RunwayViewSet, base_name='serializers-runway')
router.register(r'airport-comms', AirportCommViewSet, base_name='serializers-airportcomm')
router.register(r'members', MemberViewSet, base_name='serializers-member')
router.register(r'users', UserViewSet, base_name='serializers-user')
router.register(r'posts', PostViewSet, base_name='serializers-post')
router.register(r'comments', CommentViewSet, base_name='serializers-comment')

serializer_patterns = [
    url(r'^serializers/', include(router.urls)),
]

urlpatterns += serializer_patterns

prepair/views.py
from django.shortcuts import render
from django.http.request import QueryDict
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic.base import TemplateView
from six.moves.urllib.parse import urlparse

from rest_framework.renderers import JSONRenderer
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.viewsets import GenericViewSet as DRFGenericViewset
from rest_framework.mixins import CreateModelMixin, ListModelMixin, RetrieveModelMixin, UpdateModelMixin, \
    DestroyModelMixin

from .renderers import PrepairAPIRenderer
from api.flightplan_client import FlightPlanAPIClient
from accounts.models import Member


def index(request):
    user = request.user
    data = {}

    if request.POST:
        icao = request.POST.get('icao', None)

        client = FlightPlanAPIClient()
        response = client.get(icao=icao.lower())

        if response.get('pk'):
            pk = response.get('pk')
            return HttpResponseRedirect(reverse('dashboard') + '/?airportpk={}'.format(pk))
        else:
            error_code = response.get('error')
            if error_code == 429:
                return render(request, 'index.html', {'over_limit': True})
            elif not error_code:
                general_error = 'An Unknown error has occurred.  Contact site Admin.'
                return render(request, 'index.html', {'error_code': general_error, 'icao': icao})
            else:
                return render(request, 'index.html', {'error_code': error_code, 'icao': icao})

    if user.id:
        try:
            member = Member.objects.get(user=user)
            if member.home_airport:
                home_airport_pk = member.home_airport.pk
                home_airport_icao = member.home_airport.icao
                data = {'home_airport_pk': home_airport_pk, 'home_airport_icao': home_airport_icao}
        except Member.DoesNotExist:
            pass  # Data error, do not return empty dictionary
        except Member.MultipleObjectsReturned:
            pass  # Data error, do not return empty dictionary

    return render(request, 'index.html', data)


class DashboardTemplateView(TemplateView):
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardTemplateView, self).get_context_data(**kwargs)

        airport_pk = self.request.GET.get('airportpk', 0)
        user_id = self.request.user.id if self.request.user.id else 0
        if urlparse(self.request.path).path == '/dashboard/':
            base_redirect = 1
        else:
            base_redirect = 0

        context['airport_pk'] = airport_pk
        context['user_id'] = user_id
        context['base_redirect'] = base_redirect

        return context


class PrepairViewSet(CreateModelMixin,
                     ListModelMixin,
                     RetrieveModelMixin,
                     UpdateModelMixin,
                     DestroyModelMixin,
                     DRFGenericViewset):
    """
    Base DRF Viewset for all objects
    Default CRUD Methods are all inherited through DRF Mixins
    """

    prepair_browsable = ['get', 'head', 'options']

    renderer_classes = (JSONRenderer, PrepairAPIRenderer)
    permission_classes = (IsAuthenticatedOrReadOnly,)

    # These values are set within the subclass Model Viewsets
    prepair_model_class = None
    queryset = None
    serializer_class = None

    filter_fields = tuple()
    iexact_filter_fields = tuple()

    def filter_queryset(self, queryset=None, is_list_call=False):
        request_params = self.request.query_params

        filter_kwargs = {}
        for filter_field in self.filter_fields:
            if filter_field in request_params:
                initial_filter_field = filter_field

                if isinstance(request_params, QueryDict):
                    values_list = request_params.getlist(filter_field)
                else:
                    values_list = request_params.get(filter_field)

                # Django ORM does not support iexact__in, so must choose one or the other
                if isinstance(values_list, list) and len(values_list) > 1:
                    filter_kwargs[filter_field + '__in'] = values_list
                else:
                    if filter_field in self.iexact_filter_fields:
                        filter_field += '__iexact'
                    filter_kwargs[filter_field] = request_params[initial_filter_field]

        return self.prepair_model_class.objects.filter(**filter_kwargs)

prepair/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html ng-app="pilotApp">
  <head>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Link to CSS -->
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

  {% block head_includes %}
  {% endblock %}

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li>
                <a href="{% url 'index-view' %}">
                    <span class='glyphicon glyphicon-plane' aria-hidden="true"></span>
                </a>
              </li>
                <li>
                <a href="https://github.com/bfolks2/django-aviation">
                    <span class='glyphicon glyphicon-wrench' aria-hidden="true"></span>
                    <span class="source-text"> Source Code </span>
                </a>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                <li><p>@{{ user.username }}</p></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
              {% else %}
                <li><a href="{% url 'accounts:register-member' %}">Register</a></li>
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
              {% endif %}
            </ul>
          </div>
      </div>
    </nav>

  {% block content %}
  {% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'js/master.js' %}"></script>

  {% block scripting %}
  {% endblock %}

  </body>
</html>

prepair/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block head_includes %}
    <title>PrepAir</title>
    <!-- Link to CSS -->
    <link rel="stylesheet" href="{% static 'mydist/assets/vendor-52b14d375b4eb06d5d3284bda92f4e67.css' %}">
    <link rel="stylesheet" href="{% static 'mydist/assets/dashboard-95e167c2593bc41bd9a58d8e51bd669e.css' %}">
{% endblock %}

{% block scripting %}
    <script type="text/javascript">
        window.airport_pk = {{ airport_pk }};
        window.user_id = {{ user_id }};
        window.base_redirect = {{ base_redirect }};
    </script>

    <script src="{% static 'mydist/assets/vendor-9d8cfc931c086704d3f2a2cf7c1fd707.js' %}"></script>
    <script src="{% static 'mydist/assets/dashboard-cb78a956fa0412a725d0979d244adc5b.js' %}"></script>
{% endblock %}

{# The entire Ember app is nested within the below div #}
{% block content %}
    <div class="container main-header">
        <img src="{% static 'mydist/assets/images/departure-93812b7117fa4701f345d8cc7274e424.png' %}" style="height: 75px; width: 100px">
        <span class="large-inline">Airport Dashboard</span>
    </div>
    <input id="csrfmiddlewaretokennav" name="csrfmiddlewaretokennav" type="hidden" value="{{ csrf_token }}"/>
    <div id="emberRoot"></div>
{% endblock %}

prepair/templates/index.html
{% extends 'base.html' %}

{% block head_includes %}
    <title>PrepAir</title>
{% endblock %}

{% load static %}
{% block content %}
    <div class="container">
        <div class="main-header">
            <h1>PrepAir.com</h1>
            <p>
                Or at least that could be the name of this site if I had purchased that domain...
            </p>
            <p>
                <span class="bold-underline">Users  can search for any airport in the world.</span>  This site is
                built to allow all users to get up-to-date flight simulating information.  Anytime a user
                searches for an airport, relevant airport data, including real-time aviation weather information
                (METAR/TAF), is displayed.  Additionally, if the airport searched for by a user does not yet exist in
                this site's internal database, all static data (i.e. name, runway info, communication/frequencies, etc)
                is permanently saved into the internal database using this site's own <a href="/serializers/">REST API</a>.
                The size of this site's internal airport database grows each time a user searches for a new airport.
                All users can search across the internal database of airports. Once registered, users can also post
                their own specific reports, or even comment on other user's experiences.
            </p>
            <p>
                User Registration is left intentionally simple for the time being.  No email verification required.
                While registration is not necessary to use the site, it does add additional functionality.  (In the
                unlikely event that this site grows into the thousands of users, email-hash verification will be
                implemented to prevent spam accounts).
            </p>
            <p class="bold-text">
                ***Powered by Python/Django and Ember.js***
            </p>
        </div>
        <div class="sub-header text-center">
            <h1>Airport Search</h1>

            {% if error_code %}
                <h2 class='bg-warning text-center'>{{ error_code }}:  Unable to process your request for <em>{{ icao }}</em>.  Make sure this is an active ICAO.</h2>
            {% endif %}

            {% if over_limit %}
                <h2 class='bg-warning text-center'>Sorry, this site has reached it's limit with FlightPlanDatabase.  Please try again in a few hours.</h2>
            {% endif %}

            <form class="icao-form" method="POST">
                <div class="input-box">
                    <input id="icao-input" type="text" placeholder="Enter 3-4 digit Airport ICAO" name="icao"
                           onkeyup="validateICAO()">
                </div>
                <div class="small-text">
                    <p>Examples: KJFK, KLAX, KORD, EGLL, etc.</p>
                </div>
                <div class="main-btn">
                    <input id="submit-btn" class="btn btn-primary" type="submit" value="Search" disabled>
                </div>
                {% if home_airport_pk %}
                    <div class="home-airport-index">
                        <a href="dashboard/airport/{{ home_airport_pk }}">Home Airport ({{ home_airport_icao }})</a>
                    </div>
                {% endif %}
                {% csrf_token %}
            </form>
        </div>

        <div class="sub-header text-center">
            <h2>Just here to browse around?  You can view airports already searched for by other users <a href="/dashboard/">here</a></h2>
            <div class="disclaimer">
                <div class="small-text">
                    <p class="banner-header">External API airport data retrieved from</p>
                </div>
                <img src="{% static "media/dark_banner.png" %}"/>
                <div class="small-text">
                    <p>The data available through this site is for flight simulation use only and must not be used for real-world aviation.</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}